### ISSUE TITLE
Generating Chunks in editor mode

### ISSUE THREAD

**Issue by frieddumplings** [npruehs/bychance#7] opened 2016-10-23 00:23 UTC
Hi, I just bought the project and am extremely happy with it, however I have noticed something when generating the chunks out of play mode - the level generator will only generate a level if you move the editor window or update something. Using Version 5.3.5f1 (960ebf59018a). The loop to destroy the objects does not execute in editor mode as well ->

```
            foreach (Transform levelObject in this.LevelRoot)
            {
                Destroy(levelObject.gameObject);
            }
```
Deleting the objects manually and generating the level does work however. 
![bug1](https://cloud.githubusercontent.com/assets/12145555/19623363/938f1c28-9912-11e6-83b1-097bd3e6e5d0.jpg)

my testing was done in a new project with just this asset selected. All settings done on default.

**Comment by frieddumplings** [comment] 2016-10-23 00:34
Forgot to add - I did have to add [ExecuteInEditMode] to the top to make the chunks generate as well. 

![a1](https://cloud.githubusercontent.com/assets/12145555/19623426/97224dea-9914-11e6-85b6-499c5463090d.jpg)

**Comment by frieddumplings** [comment] 2016-10-23 02:01
Found the issue, 
https://docs.unity3d.com/ScriptReference/ExecuteInEditMode.html

> By default, script components are only executed in play mode. By adding this attribute, each script component will also have its callback functions executed while the Editor is not in playmode.
> 
>**The functions are not called constantly like they are in play mode.**
> **- Update is only called when something in the scene changed.**
> - OnGUI is called when the Game View recieves an Event.
> - **OnRenderObject and the other rendering callback functions are called on every repaint of the Scene View or Game View.**

Possible Solution Outlined below:
Add in [ExecuteInEditMode] as shown above first.
I modified the destroy object code as it was not updating on a frame by frame basis:
 ```
       [ContextMenu("Generate Level")]
        public void GenerateLevel()
        {
            // Create new level generator.
            this.CreateLevelGenerator();
            
            // Clear current level.
            var children = this.LevelRoot.GetComponentsInChildren<Transform>();
            for (int i = 0; i < children.Count(); i++)
            {
                if (children[i] != null && children[i].gameObject != this.LevelRoot.gameObject)
                    DestroyImmediate(children[i].gameObject);
            }
```
So if a new method is added with OnRenderObject that only runs when in the editor 
and we disable the update method in the editor mode it does work, I am sure theres a better way to do it than this but for now it seems to run as intended. Abusing OnRenderObject seems a bit hacky, oh well.

```
//At the top of Update Method
            if (!Application.isPlaying)
                return;
```


 
```
//New method at the bottom.
        public void OnRenderObject()
        {
            #if UNITY_EDITOR
            if (!this.generating)
            {
                return;
            }

            // Add next chunk.
            if (this.levelChunkLibrary == null || this.level == null)
                return;
            this.generating = this.levelGenerator.AddChunk(this.levelChunkLibrary, this.level, this.random);

            if (this.generating)
            {
                return;
            }

            // Start post-processing.
            this.levelGenerator.PostProcessLevel(this.level);

            // Validate generated level.
            if (!this.ValidateLevel())
            {
                ++this.tries;
                this.GenerateLevelIteration();
                return;
            }

            // Instantiate level objects.
            this.InstantiateLevel();
            #endif
        }

        #endregion
    }
```

**Comment by npruehs** [comment] 2016-10-23 09:50
Hey @frieddumplings! Thanks for the report! I can confirm that generating levels in the editor seems to be broken in the current release. This is most probably due to the changes made to generate the levels asynchronously, in order to be able to show progress bars ingame. This will be fixed in the next release.

**Comment by npruehs** [comment] 2016-10-23 13:52
New version has been submitted to the asset store. Your fix will be available as soon as the submission has passed.

**Closed by npruehs** 2016-10-23 13:52 UTC
Labels: bug, unity3d
